export const UI = {
  en: {
    dashboard_title: 'RankUp Dashboard',
    path_to: 'Path to',
    status: 'Status',
    xp: 'Experience Points',
    time_in_rank: 'Time in Rank',
    days: 'DAYS',
    todays_quests: "Today's Quests",
    completed: 'Completed',
    claim: 'Claim',
    locked: 'Locked',
    challenge_active: 'Challenge Active',
    promotion: 'PROMOTION',
    rank_up_eval: 'Rank Up Evaluation',
    try_level_up: 'Try to Level Up',
    days_remaining: 'Days Remaining',
    trophy_room: 'Trophy Room',
    your_achievements: 'Your Achievements',
    config: 'Config',
    manage_data: 'Manage Data',
    data_management: 'Data Management',
    export_backup: 'Export Backup (.json)',
    import_backup: 'Import Backup',
    danger_zone: 'Danger Zone',
    reset_progress: 'Reset All Progress',
    system_locked: 'System Locked',
    return_to_base: 'Return to Base',
    evaluation_mode: 'Evaluation Mode',
    start_timer: 'Start Timer',
    complete_eval: 'Complete Evaluation',
    objectives: 'Objectives',
    home: 'Home',
    trophies: 'Trophies',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    age: 'Age',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    current_level: 'Current Level',
    level_novice: 'Novice',
    level_novice_desc: 'Starting from scratch',
    level_experienced: 'Experienced',
    level_experienced_desc: 'Returning to form',
    level_veteran: 'Veteran',
    level_veteran_desc: 'Just need the system',
    inventory: 'Available Inventory (Optional)',
    treadmill: 'Treadmill',
    pullup_bar: 'Pull-up Bar',
    dumbbells: 'Dumbbells',
    rings: 'Rings',
    initialize: 'Initialize System',
    proceed: 'Proceed',
    establish_baseline: 'Establish your',
    baseline: 'Baseline',
    rank: 'Rank',
    day_streak: 'Day Streak',
    language: 'Language',
    confirm_reset: 'Are you absolutely sure you want to reset all progress? This action cannot be undone.',
    import_success: 'Data imported successfully!',
    import_error: 'Invalid backup file structure.',
    import_parse_error: 'Error parsing JSON file.',
    test: 'Test',
    fail_desc_1: 'You failed the recent evaluation. Neural pathways need recovery. Next attempt available in roughly ',
    fail_desc_2: 'h',
    rest_day_select: 'Choose a Rest Day',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    rest_quest_title: 'Full Recovery and Rest',
    penalty_title: 'Training Missed!',
    penalty_partial: "You didn't complete all quests. Streak reset to 0.",
    penalty_full: 'You missed your training! Streak reset to 0, rank progress reduced by 2 days.',
    debug_mode: 'Debug Mode',
    force_phase: 'Force Phase',
    force_rank: 'Force Rank',
    simulate_day: 'Simulate Day of Week',
    test_level_up: 'Test Level Up',
    challenge_yourself: 'Challenge Yourself',
    challenge_accepted: 'Challenge Accepted!',
    required_inventory: 'Required Inventory for Next Rank',
    phase_i: 'Phase I: Awakening',
    phase_ii: 'Phase II: Tempering',
    phase_iii: 'Phase III: Limit',
    week_days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  },
  ru: {
    dashboard_title: 'Трекер RankUp',
    path_to: 'Путь к',
    status: 'Статусу',
    xp: 'Очки Опыта',
    time_in_rank: 'Дней в ранге',
    days: 'ДНЕЙ',
    todays_quests: 'Задания на сегодня',
    completed: 'Выполнено',
    claim: 'Забрать',
    locked: 'Заблокировано',
    challenge_active: 'Испытание Доступно',
    promotion: 'ПОВЫШЕНИЕ',
    rank_up_eval: 'Экзамен на Повышение',
    try_level_up: 'Начать Испытание',
    days_remaining: 'Дней осталось',
    trophy_room: 'Зал Славы',
    your_achievements: 'Твои Достижения',
    config: 'Настройки',
    manage_data: 'Управление Данными',
    data_management: 'Хранение',
    export_backup: 'Экспорт Прогресса (.json)',
    import_backup: 'Импорт Прогресса',
    danger_zone: 'Опасная Зона',
    reset_progress: 'Сбросить Весь Прогресс',
    system_locked: 'Система Заблокирована',
    return_to_base: 'Вернуться на Базу',
    evaluation_mode: 'Режим Экзамена',
    start_timer: 'Запустить Таймер',
    complete_eval: 'Завершить Испытание',
    objectives: 'Цели',
    home: 'Главная',
    trophies: 'Трофеи',
    gender: 'Пол',
    male: 'Мужской',
    female: 'Женский',
    age: 'Возраст',
    height: 'Рост (см)',
    weight: 'Вес (кг)',
    current_level: 'Текущий Уровень',
    level_novice: 'Новичок',
    level_novice_desc: 'Никогда особо не тренировался',
    level_experienced: 'Был опыт',
    level_experienced_desc: 'Раньше занимался, хочу вернуться',
    level_veteran: 'Ветеран',
    level_veteran_desc: 'Знаю что делать, нужна система',
    inventory: 'Инвентарь (Опционально)',
    treadmill: 'Беговая дорожка',
    pullup_bar: 'Турник',
    dumbbells: 'Гантели/Гири',
    rings: 'Кольца',
    initialize: 'Инициализация Системы',
    proceed: 'Продолжить',
    establish_baseline: 'Установи свою',
    baseline: 'Базу',
    rank: 'Ранг',
    day_streak: 'Дней Подряд',
    language: 'Язык',
    confirm_reset: 'Вы абсолютно уверены, что хотите сбросить весь прогресс? Это действие нельзя отменить.',
    import_success: 'Данные успешно импортированы!',
    import_error: 'Неверная структура файла резервной копии.',
    import_parse_error: 'Ошибка при чтении JSON файла.',
    test: 'Тест',
    fail_desc_1: 'Испытание провалено. Нейронным путям требуется восстановление. Следующая попытка примерно через ',
    fail_desc_2: 'ч',
    rest_day_select: 'Выбери день полного отдыха',
    sunday: 'Воскресенье',
    monday: 'Понедельник',
    tuesday: 'Вторник',
    wednesday: 'Среда',
    thursday: 'Четверг',
    friday: 'Пятница',
    saturday: 'Суббота',
    rest_quest_title: 'Полное восстановление и отдых',
    penalty_title: 'Тренировка пропущена!',
    penalty_partial: 'Вы не выполнили все задания. Стрик сброшен до 0.',
    penalty_full: 'Вы пропустили день! Стрик сброшен до 0, прогресс ранга уменьшен на 2 дня.',
    debug_mode: 'Режим Отладки',
    force_phase: 'Сменить фазу',
    force_rank: 'Сменить ранг',
    simulate_day: 'Симуляция дня недели',
    test_level_up: 'Тест Испытания',
    challenge_yourself: 'Брось себе вызов',
    challenge_accepted: 'Вызов принят!',
    required_inventory: 'Требуемый инвентарь для следующего ранга',
    phase_i: 'Фаза I: Пробуждение',
    phase_ii: 'Фаза II: Закалка',
    phase_iii: 'Фаза III: Предел',
    week_days: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота']
  }
};
